### ISSUE TITLE
Debugger doesn't work

### ISSUE THREAD

**Issue by danisal** [thingsboard/thingsboard-extensions#53]
Hi, I'm having a problem using the `debugger` keyword; it doesn't work when placed in a component `.ts` file. It works fine inside the thingsboard widget editor but not on the tb-extensions repository. 

I don't know if this is an angular problem or if I need to enable something in TB. 

I appreciate any help 🙏

**Comment by danisal** [comment]
@vvlladd28 can you provide any information about this? Thanks in advance 🙏

**Comment by danisal** [comment]
Is there a way we can enable the debugger?

**Comment by skewty** [comment]
TS source maps aren't working either which makes debugging horrible.

I tried: `"sourceMap": true` in `tsconfig.builders.json` but that didn't change the generated `dist/system/thingsboard-extension-widgets.js` file we are instructed to use as a resource in `README.md`. 

I also can't seem to get Redux DevTools working with my extensions due to the way everything is compiled / packaged.

Is there any way to configure ThingsBoard server and the builder to provide a typical development environment?

**Comment by danisal** [comment]
Hi @skewty the source maps are working for me, I've just upload them with the main js file to the server. The debugger, is another story, you need to actually change the `ng-packagr`, so I've made a patch. Here what I've added:

```js
// on the rollup config file - widgets/node_modules/ng-packagr/lib/flatten/rollup.js -> 
const bundle = await rollup.rollup({
...
            terser({
              compress: {
                drop_debugger: false
              }
            })
...
})
...
```

Compress options - https://github.com/terser/terser#compress-options

**Comment by skewty** [comment]
Trying to use this repo and `mvn clean install -P yarn-start` in widgets folder after making the addition you provided above (see end of code snippet below) to `widgets/builders/node_modules/ng-packagr/lib/flatten/rollup.js` (path is slightly different than what you wrote in your post above)

```js
    const bundle = await rollup.rollup({
        context: 'this',
        external: moduleId => isExternalDependency(moduleId),
        cache: (_a = opts.cache) !== null && _a !== void 0 ? _a : (cacheDirectory ? await (0, cache_1.readCacheEntry)(cacheDirectory, opts.cacheKey) : undefined),
        input: opts.entry,
        plugins: [
            (0, plugin_node_resolve_1.default)(),
            (0, plugin_json_1.default)(),
            (0, file_loader_plugin_1.fileLoaderPlugin)(opts.fileCache),
            opts.downlevel ? (0, downlevel_plugin_1.downlevelCodeWithTscPlugin)() : undefined,
        ],
        onwarn: warning => {
            switch (warning.code) {
                case 'CIRCULAR_DEPENDENCY':
                case 'UNUSED_EXTERNAL_IMPORT':
                case 'THIS_IS_UNDEFINED':
                    break;
                default:
                    log.warn(warning.message);
                    break;
            }
        },
        preserveSymlinks: true,
        // Disable treeshaking when generating bundles
        // see: https://github.com/angular/angular/pull/32069
        treeshake: false,
        // Debug doesn't work fix - https://github.com/thingsboard/thingsboard-extensions/issues/53
        terser({ compress: { drop_debugger: false } })
    });
```
this is what is generated
![image](https://github.com/thingsboard/thingsboard-extensions/assets/9087223/e54e559a-5208-42a6-ac34-d5c70fbeaab6)

I appears the .map and .ts files are all in there but when I go into Chrome I am still only getting mjs files with no mapping to ts source mapping.

I even tried changing `widgets/builders/tsconfig.builders.json` to set `sourceMap: true` and that didn't help either.

![image](https://github.com/thingsboard/thingsboard-extensions/assets/9087223/3e2c9051-011b-4aee-9fd2-a7c827354b1f)

**Comment by danisal** [comment]
Sorry, I didn't understand what are you trying to accomplish. Also, what is the path you are using in the thingsboard? Because it should be this one `dist/widget-extension/system/thingsboard-extension-widgets.js` that you should be using on the Thingsboard Resource tab. 

I'm using this approach with a local docker container, and it's working fine; I can see the correct `.ts` file on the console when I console something or debug it.

Let me know if there is something I can help with.

**Comment by skewty** [comment]
I have a library of widgets for configuring some custom gateways that extend ThingsBoard's capabilities.
One gateway in particular has state complex enough to warrant the use of the [NgRx Store](https://ngrx.io/docs).
The existing (from ThingsBoard) `PageComponent` already injects `store` so I wanted to just add to it as is typical / expected.

The follow up problem, as mentioned above, is that **Redux DevTools extension** doesn't work because ThingsBoard itself is running in "Production" mode when using the Docker images.

Try to debug code when you are working with minified sources and w/o tools like the Redux DevTools extension is very time consuming. We are nearly to the point that moving to another platform is cheaper and better. It would be a sad good bye.
